matrix:
  include:
    - git:
        submodules: false
      language: python
      install:
        - pip install -r requirements.txt
      script:
        - python -m pytest
    - git:
        submodules: false
      language: c++
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            # update to a compiler supporting c++11
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      script:
        - cd contour_visualization/cmodule
        - mkdir build
        - cd build
        - cmake ..
        - make
        - ./tests/runBlendingOperatorsUnitTests
        - ./tests/runPictureMergeUnitTests
        - ctest